### ISSUE TITLE
maven error

### ISSUE THREAD

**Issue by yoh310** [Robothy/sdwebui-java-sdk#9]
![image](https://github.com/Robothy/sdwebui-java-sdk/assets/35712597/19f2c63c-144d-42ca-9fc8-41d66cfcf05f)
maven error，tks

**Comment by Robothy** [comment]
Could you try other Maven mirrors, like Tencent?

https://mirrors.tencent.com/help/maven.html

**Comment by TeamSussy** [comment]
I'm currently running into the same issue, I tried using the google mirror and the tencent mirror as well. 
![image](https://github.com/user-attachments/assets/57210dfa-692e-42ea-bf39-ad837f14bbf7)

**Comment by Robothy** [comment]
@TeamSussy Try to add the Maven Central Repository to your project.

**Comment by TeamSussy** [comment]
I did, running into the same issue. Oddly enough intelij will run and compile it with no issue but i can't jar it due to this.
